name: Hello.
pygments: true
url: http://eric.ritchey.io
timezone: America/Los Angeles
permalink: pretty
# markdown: redcarpet
# redcarpet:
#   extensions: [footnotes]

# include: [_projects]
# projects: [bingo]
# future: false